sudo: required 
dist: trusty 
services: docker 
before_script:
  - python listFiles.py
script: 
  - wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh 
  - chmod +x latexdockercmd.sh 
  - “./latexdockercmd.sh latexmk -xelatex -interaction=nonstopmode -halt-on-error SongBook.tex -outdir=./_build”