sudo: required
dist: trusty
services: docker
before_script:
- python listFiles.py
script:
- chmod +x latexdockercmd.sh
- "latexdockercmd.sh latexmk -xelatex -interaction=nonstopmode -halt-on-error -pdf SongBook.tex"
- "songidx titleidx.sxd titleidx.sbx"
- "latexdockercmd.sh latexmk -xelatex -interaction=nonstopmode -halt-on-error -pdf SongBook.tex"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: SongBook.pdf
  on:
    repo: jensdufour/SongBook
