sudo: required
dist: trusty
services: docker
before_script:
- python listFiles.py
script:
- chmod +x latexdockercmd.sh
- docker pull firilith/docker-tectonic
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind firilith/docker-tectonic /bin/sh -c "tectonic --keep-intermediates --reruns 0 SongBook.tex; songidx titleidx.sxd titleidx.sbx; tectonic SongBook.tex"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: SongBook.pdf
  on:
    repo: jensdufour/SongBook
