sudo: required
dist: trusty
services: docker
before_script:
- python listFiles.py
script:
- docker pull blang/latex:ubuntu
- docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ubuntu /bin/sh -c "latexmk -xelatex -f -interaction=nonstopmode -halt-on-error -pdf -shell-escape SongBook.tex; ./songidx titleidx.sxd titleidx.sbx;latexmk -xelatex -f -interaction=nonstopmode -halt-on-error -pdf -shell-escape SongBook.tex;"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: SongBook.pdf
  on:
    repo: jensdufour/SongBook