sudo: required
dist: trusty
services: docker
before_script:
- python listFiles.py
script:
- docker pull blang/latex:ubuntu
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind blang/latex:ubuntu /bin/sh -c "latexmk -xelatex -interaction=nonstopmode -halt-on-error -pdf -shell-escape SongBook.tex; ./songidx titleidx.sxd titleidx.sbx;latexmk -xelatex -interaction=nonstopmode -halt-on-error -pdf -shell-escape SongBook.tex;"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: SongBook.pdf
  on:
    repo: jensdufour/SongBook
